version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-melodia
    environment:
      MYSQL_DATABASE: melodia
      MYSQL_USER: fauzan
      MYSQL_PASSWORD: passfauzan
      MYSQL_ROOT_PASSWORD: melodiapass
    ports:
      - "3308:3306"  # <-- Ganti jadi 3306 di sebelah kanan
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
